# Generated by Django 3.2.13 on 2022-06-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_plot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
