# Generated by Django 3.2.13 on 2022-06-11 19:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name=[]),
        ),
    ]
