# Generated by Django 3.2.13 on 2022-06-13 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_plot_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
