# Generated by Django 3.2.13 on 2022-06-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_plot_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='owner',
            new_name='owner_name',
        ),
    ]
