# Generated by Django 4.0.6 on 2022-07-10 12:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_owner_plot_owner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Plot', 'verbose_name_plural': 'Plots'},
        ),
        migrations.AddField(
            model_name='plot',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
