# Generated by Django 4.0.6 on 2022-07-18 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_plot_plot_plot_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
