# Generated by Django 4.0.6 on 2022-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_plot_address_alter_plot_hometown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plot',
            name='hometown',
            field=models.CharField(default='test', max_length=54),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plot',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plot',
            name='zone',
            field=models.CharField(max_length=50),
        ),
    ]
